---
title: "Expanding the Tent: Undergraduate Majors in Data Science"
output:
  github_document:
    html_preview: true
---

## JSM 2018

#### Expanding the Tent: Undergraduate Majors in Data Science — Invited Papers

Session 651:	Thu, 8/2/2018, 10:30 AM - 12:20 PM	CC-West 203

(https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215338)

Sponsors:

- Section on Statistical Education 
- Section on Statistical Learning and Data Science 
- Section on Statistical Computing

Organizer & Chair: Ben Baumer, Smith College

- 10:35 AM	Dismantling Math, Stats, and CS Silos: PCMI Guidelines for Undergraduate Majors in Data Science  
    - Albert Y. Kim, Smith College
- 10:50 AM	Pathways Through the Major in Statistical and Data Science at Smith  
    - Randi L. Garcia, Smith College
- 11:05 AM	Herding Cats: Pros and Cons of a Large-Team Approach to Data Science at a Major Research University  
    - David Hunter, Penn State University
- 11:20 AM	Designing a Group Major in Data Science  
    - Deborah Nolan, University of California, Berkeley
- 11:35 AM	Discussant:   
    - Joseph Blitzstein, Harvard University
- 11:50 AM	Discussant:   
    - Mine Cetinkaya-Rundel, Duke University
- 12:05 PM	Floor Discussion
